// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDEYscx7uga1xXHIJFn0Q0vscu1msiE1k',
    appId: '1:6261305612:web:091a3d6fd60b363fac9929',
    messagingSenderId: '6261305612',
    projectId: 'devhub-d1367',
    authDomain: 'devhub-d1367.firebaseapp.com',
    storageBucket: 'devhub-d1367.firebasestorage.app',
    measurementId: 'G-BJYZ3HT6SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrF2KjLDetuaqiDe7AjMSGUegMnGngAxc',
    appId: '1:6261305612:android:e91f4847be1667c5ac9929',
    messagingSenderId: '6261305612',
    projectId: 'devhub-d1367',
    storageBucket: 'devhub-d1367.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2QJVhwkkBHHQJ-XMm5pXRbU_1ZXYRIQs',
    appId: '1:6261305612:ios:d1cf26cf53059473ac9929',
    messagingSenderId: '6261305612',
    projectId: 'devhub-d1367',
    storageBucket: 'devhub-d1367.firebasestorage.app',
    iosBundleId: 'com.example.devHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2QJVhwkkBHHQJ-XMm5pXRbU_1ZXYRIQs',
    appId: '1:6261305612:ios:d1cf26cf53059473ac9929',
    messagingSenderId: '6261305612',
    projectId: 'devhub-d1367',
    storageBucket: 'devhub-d1367.firebasestorage.app',
    iosBundleId: 'com.example.devHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDEYscx7uga1xXHIJFn0Q0vscu1msiE1k',
    appId: '1:6261305612:web:02a646b39f55cc7cac9929',
    messagingSenderId: '6261305612',
    projectId: 'devhub-d1367',
    authDomain: 'devhub-d1367.firebaseapp.com',
    storageBucket: 'devhub-d1367.firebasestorage.app',
    measurementId: 'G-GQH4SH3LMH',
  );
}
